### PR TITLE
Added customization particles path and fix typo

### PR DESCRIPTION
**Pull request by Artur-Wisniewski**
Regarding the issue [Custom particles #18](https://github.com/funwithflutter/flutter_confetti/issues/18) I added a variable that is holding a function that returns a custom Path and takes a Size type parameter. 

Gif

### CODE REVIEW

**Comment by funwithflutter** [comment]
This is really great! Thanks! I'm exploring the possibility of also passing in images (maybe whole widgets). But this is great! Can you add your stars to the example please? Or just paste the path down here and I'll add it.

**Comment by funwithflutter** [comment]
Closses #31

**Comment by Artur-Wisniewski** [comment]
Hi! I passed a function that is creating stars. 
```
Path drawStar(Size size) {
    // Method to convert degree to radians
    double degToRad(double deg) => deg * (pi / 180.0);

    const numberOfPoints = 5;
    final halfWidth = size.width / 2;
    final externalRadius = halfWidth;
    final internalRadius = halfWidth / 2.5;
    final degreesPerStep = degToRad(360 / numberOfPoints);
    final halfDegreesPerStep = degreesPerStep / 2;
    final path = Path();
    final fullAngle = degToRad(360);
    path.moveTo(size.width, halfWidth);

    for (double step = 0; step < fullAngle; step += degreesPerStep) {
      path.lineTo(halfWidth + externalRadius * cos(step),
          halfWidth + externalRadius * sin(step));
      path.lineTo(halfWidth + internalRadius * cos(step + halfDegreesPerStep),
          halfWidth + internalRadius * sin(step + halfDegreesPerStep));
    }
    path.close();
    return path;
  }
```

**Comment by funwithflutter** [comment]
Thanks!

**Pull request merged**
